spring:
  datasource:
    url: jdbc:postgresql://db:5432/currency_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml