spring:
  datasource:
    url: jdbc:postgresql://db:5432/currencies
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml